"use client";
import React, { useState } from "react";
import { Copy, Check, ArrowLeft, Terminal } from "lucide-react";
import Link from "next/link";

const DockerTutorial = () => {
  const tutorials = [
    {
      title: "Introduction to Docker",
      content:
        "Docker is a platform that enables developers to package applications into containers—standardized executable components combining application source code with the operating system (OS) libraries and dependencies required to run that code in any environment.",
      examples: [
        {
          code: `docker --version`,
          description: "Check your Docker installation version",
        },
        {
          code: `docker run hello-world`,
          description: "Run your first Docker container to verify installation",
        },
      ],
    },
    {
      title: "Docker Images and Containers",
      content:
        "Docker images are read-only templates used to create containers. Containers are running instances of Docker images.",
      examples: [
        {
          code: `docker pull nginx:latest`,
          description: "Pull the latest nginx image from Docker Hub",
        },
        {
          code: `docker images`,
          description: "List all Docker images on your system",
        },
        {
          code: `docker run -d -p 8080:80 --name my-nginx nginx`,
          description:
            "Run nginx container in detached mode\n-d: Detached mode\n-p: Port mapping (host:container)\n--name: Container name",
        },
        {
          code: `docker ps`,
          description: "List all running containers",
        },
        {
          code: `docker ps -a`,
          description: "List all containers (including stopped ones)",
        },
      ],
    },
    {
      title: "Dockerfile Basics",
      content:
        "A Dockerfile is a text document that contains all the commands to assemble a Docker image. It automates the image creation process.",
      examples: [
        {
          code: `FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "start"]`,
          description:
            "A basic Dockerfile for a Node.js application\nFROM: Base image\nWORKDIR: Set working directory\nCOPY: Copy files\nRUN: Execute commands\nEXPOSE: Document port\nCMD: Default command",
        },
        {
          code: `docker build -t my-app:1.0 .`,
          description:
            "Build a Docker image from Dockerfile\n-t: Tag the image\n.: Build context (current directory)",
        },
      ],
    },
    {
      title: "Docker Container Management",
      content:
        "Learn essential commands to manage Docker containers throughout their lifecycle.",
      examples: [
        {
          code: `docker start my-nginx`,
          description: "Start a stopped container",
        },
        {
          code: `docker stop my-nginx`,
          description: "Stop a running container gracefully",
        },
        {
          code: `docker restart my-nginx`,
          description: "Restart a container",
        },
        {
          code: `docker rm my-nginx`,
          description: "Remove a stopped container",
        },
        {
          code: `docker rm -f my-nginx`,
          description: "Force remove a running container",
        },
        {
          code: `docker logs my-nginx`,
          description: "View container logs",
        },
        {
          code: `docker exec -it my-nginx /bin/bash`,
          description:
            "Execute interactive bash shell inside container\n-it: Interactive terminal",
        },
      ],
    },
    {
      title: "Docker Volumes",
      content:
        "Docker volumes are the preferred mechanism for persisting data generated by and used by Docker containers.",
      examples: [
        {
          code: `docker volume create my-volume`,
          description: "Create a named volume",
        },
        {
          code: `docker run -d -v my-volume:/data --name my-container nginx`,
          description:
            "Mount a volume to a container\n-v: Volume mapping (volume:container-path)",
        },
        {
          code: `docker volume ls`,
          description: "List all volumes",
        },
        {
          code: `docker volume inspect my-volume`,
          description: "View detailed information about a volume",
        },
      ],
    },
    {
      title: "Docker Compose",
      content:
        "Docker Compose is a tool for defining and running multi-container Docker applications using a YAML file.",
      examples: [
        {
          code: `version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
  
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:`,
          description:
            "A docker-compose.yml file defining a web server and database\nservices: Define containers\nports: Port mappings\nvolumes: Volume mounts\nenvironment: Environment variables",
        },
        {
          code: `docker-compose up -d`,
          description:
            "Start all services defined in docker-compose.yml in detached mode",
        },
        {
          code: `docker-compose down`,
          description:
            "Stop and remove all containers, networks defined in compose file",
        },
        {
          code: `docker-compose logs -f`,
          description: "View logs from all services\n-f: Follow log output",
        },
      ],
    },
    {
      title: "Docker Networking",
      content:
        "Docker networking allows containers to communicate with each other and the outside world.",
      examples: [
        {
          code: `docker network create my-network`,
          description: "Create a custom network",
        },
        {
          code: `docker network ls`,
          description: "List all networks",
        },
        {
          code: `docker run -d --network my-network --name app1 nginx`,
          description: "Run a container on a specific network",
        },
        {
          code: `docker network inspect my-network`,
          description: "View detailed information about a network",
        },
      ],
    },
    {
      title: "Docker Cleanup Commands",
      content:
        "Keep your Docker environment clean by removing unused containers, images, and volumes.",
      examples: [
        {
          code: `docker system prune`,
          description:
            "Remove all stopped containers, unused networks, dangling images",
        },
        {
          code: `docker system prune -a`,
          description:
            "Remove all unused images, not just dangling ones\n-a: All unused images",
        },
        {
          code: `docker image prune`,
          description: "Remove unused images",
        },
        {
          code: `docker volume prune`,
          description: "Remove unused volumes",
        },
        {
          code: `docker container prune`,
          description: "Remove all stopped containers",
        },
      ],
    },
  ];

  const [copiedIndex, setCopiedIndex] = useState<string | null>(null);

  const copyToClipboard = (text: string, idx: string) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(idx);
    setTimeout(() => {
      setCopiedIndex(null);
    }, 2000);
  };

  return (
    <div className="min-h-screen mt-16 bg-white pt-16 pb-12 relative">
      <div className="absolute top-5 left-4 md:left-8">
        <Link
          href="/devops"
          className="inline-flex items-center px-4 py-2 text-[#A435F0] hover:text-white border-2 border-[#A435F0] hover:bg-[#A435F0] rounded-sm transition-all duration-300 group"
        >
          <ArrowLeft className="w-4 h-4 mr-2 transform group-hover:translate-x-[-2px] transition-transform" />
          Back to DevOps
        </Link>
      </div>

      <div className="max-w-4xl mx-auto px-4">
        <div className="flex items-center gap-3 mb-4">
          <Terminal className="w-10 h-10 text-[#A435F0]" />
          <h1 className="text-4xl font-bold text-[#000000]">Docker Tutorial</h1>
        </div>
        <p className="text-gray-600 text-lg mb-8">
          Master Docker fundamentals with our comprehensive tutorial. Learn
          containerization, image management, and orchestration through
          practical examples.
        </p>

        {/* Video Section */}
        <div className="mb-12">
          <h2 className="text-2xl font-semibold text-[#000000] mb-4">
            Video Tutorial
          </h2>
          <div className="aspect-video w-full">
            <iframe
              width="100%"
              height="100%"
              src="https://www.youtube.com/embed/exmSJpJvIPs?si=wk59usQYSljxN37h"
              title="Docker Tutorial for Beginners"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
              className="rounded-sm"
            ></iframe>
          </div>
        </div>

        <div className="space-y-8">
          {tutorials.map((tutorial, index) => (
            <div
              key={index}
              className="bg-white border border-gray-200 rounded-sm p-6 hover:border-[#A435F0] transition-all duration-300 hover:shadow-lg"
            >
              <h2 className="text-2xl font-semibold text-[#000000] mb-4">
                {tutorial.title}
              </h2>
              <p className="text-gray-600 mb-6">{tutorial.content}</p>

              <div className="bg-gray-50 rounded-sm p-4">
                <h3 className="text-lg font-medium text-[#000000] mb-3">
                  Examples:
                </h3>
                <div className="space-y-4">
                  {tutorial.examples.map((example, idx) => {
                    const uniqueId = `${index}-${idx}`;
                    return (
                      <div key={idx} className="space-y-2">
                        <div className="relative">
                          <pre className="bg-gray-100 p-3 rounded-sm overflow-x-auto">
                            <code className="text-[#A435F0]">
                              {example.code}
                            </code>
                          </pre>
                          <button
                            onClick={() =>
                              copyToClipboard(example.code, uniqueId)
                            }
                            className="absolute top-2 right-2 p-2 rounded-sm bg-gray-200/50 backdrop-blur-sm text-gray-600 hover:bg-[#A435F0]/20 hover:text-[#A435F0] transition-all duration-300 transform active:scale-95"
                            title="Copy to clipboard"
                          >
                            {copiedIndex === uniqueId ? (
                              <Check
                                size={16}
                                className="text-green-400 animate-in fade-in duration-300"
                              />
                            ) : (
                              <Copy size={16} />
                            )}
                          </button>
                        </div>
                        <p className="text-gray-600 text-sm whitespace-pre-line pl-2 border-l-2 border-[#A435F0]">
                          {example.description}
                        </p>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Quick Reference Card */}
        <div className="mt-12 bg-gradient-to-br from-[#A435F0]/5 to-[#A435F0]/10 border border-[#A435F0]/20 rounded-sm p-6">
          <h2 className="text-2xl font-semibold text-[#000000] mb-4 flex items-center gap-2">
            <Terminal className="w-6 h-6 text-[#A435F0]" />
            Quick Reference
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
            <div>
              <h3 className="font-semibold text-[#A435F0] mb-2">
                Essential Commands
              </h3>
              <ul className="space-y-1 text-gray-700">
                <li>
                  <code className="bg-white px-2 py-0.5 rounded">
                    docker ps
                  </code>{" "}
                  - List running containers
                </li>
                <li>
                  <code className="bg-white px-2 py-0.5 rounded">
                    docker images
                  </code>{" "}
                  - List images
                </li>
                <li>
                  <code className="bg-white px-2 py-0.5 rounded">
                    docker pull
                  </code>{" "}
                  - Download image
                </li>
                <li>
                  <code className="bg-white px-2 py-0.5 rounded">
                    docker build
                  </code>{" "}
                  - Build image
                </li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold text-[#A435F0] mb-2">
                Best Practices
              </h3>
              <ul className="space-y-1 text-gray-700">
                <li>✓ Use official base images</li>
                <li>✓ Minimize layer count</li>
                <li>✓ Use .dockerignore files</li>
                <li>✓ Don&apos;t run as root user</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DockerTutorial;
